package tp;


/**
* tp/LM.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LM.idl
* mercredi 18 mai 2016 10 h 34 CEST
*/

public interface LM extends LMOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface LM
