package tp;

/**
* tp/LMHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LM.idl
* mardi 17 mai 2016 11 h 07 CEST
*/

public final class LMHolder implements org.omg.CORBA.portable.Streamable
{
  public tp.LM value = null;

  public LMHolder ()
  {
  }

  public LMHolder (tp.LM initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = tp.LMHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    tp.LMHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return tp.LMHelper.type ();
  }

}
