package tp;


/**
* tp/LMOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LM.idl
* mercredi 18 mai 2016 10 h 34 CEST
*/

public interface LMOperations 
{
  String theme ();
  String moderator ();
  boolean postMessage (tp.Message m);
  tp.Message getMessage (String title);
  boolean removeMessage (String title);
} // interface LMOperations
