package tp;


/**
* tp/LMPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LM.idl
* mercredi 18 mai 2016 10 h 34 CEST
*/

public abstract class LMPOA extends org.omg.PortableServer.Servant
 implements tp.LMOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_theme", new java.lang.Integer (0));
    _methods.put ("_get_moderator", new java.lang.Integer (1));
    _methods.put ("postMessage", new java.lang.Integer (2));
    _methods.put ("getMessage", new java.lang.Integer (3));
    _methods.put ("removeMessage", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // tp/LM/_get_theme
       {
         String $result = null;
         $result = this.theme ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // tp/LM/_get_moderator
       {
         String $result = null;
         $result = this.moderator ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // tp/LM/postMessage
       {
         tp.Message m = tp.MessageHelper.read (in);
         boolean $result = false;
         $result = this.postMessage (m);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // tp/LM/getMessage
       {
         String title = in.read_string ();
         tp.Message $result = null;
         $result = this.getMessage (title);
         out = $rh.createReply();
         tp.MessageHelper.write (out, $result);
         break;
       }

       case 4:  // tp/LM/removeMessage
       {
         String title = in.read_string ();
         boolean $result = false;
         $result = this.removeMessage (title);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:tp/LM:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public LM _this() 
  {
    return LMHelper.narrow(
    super._this_object());
  }

  public LM _this(org.omg.CORBA.ORB orb) 
  {
    return LMHelper.narrow(
    super._this_object(orb));
  }


} // class LMPOA
