package tp;

/**
* tp/MessageHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LM.idl
* mardi 17 mai 2016 11 h 07 CEST
*/

public final class MessageHolder implements org.omg.CORBA.portable.Streamable
{
  public tp.Message value = null;

  public MessageHolder ()
  {
  }

  public MessageHolder (tp.Message initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = tp.MessageHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    tp.MessageHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return tp.MessageHelper.type ();
  }

}
